package co.blocke.scalajack
package internal

import scala.quoted.*

/** This is a fantastic object contributed by Aleksander Rainko.
  * It will display the code generated by a macro to the console on compile:
  *
  *     internal.CodePrinter.code {
  *       sj[Record]
  *     }
  */
//$COVERAGE-OFF$3rd party library
object CodePrinter {
  inline def structure[A](inline value: A) = ${ structureMacro('value) }

  private def structureMacro[A: Type](value: Expr[A])(using Quotes): Expr[A] = {
    import quotes.reflect.*

    val struct = Printer.TreeStructure.show(value.asTerm)
    report.info(struct)
    value.asTerm.changeOwner(Symbol.spliceOwner).asExprOf[A]
  }

  inline def code[A](inline value: A): A = ${ codeMacro('value) }

  private def codeMacro[A: Type](value: Expr[A])(using Quotes): Expr[A] = {
    import quotes.reflect.*
    val struct = Printer.TreeShortCode.show(value.asTerm)
    report.info(struct)
    value
  }
}
//$COVERAGE-ON$
