
name: Coveralls Publish

on:
  pull_request:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


concurrency:
  group: ${{ github.workflow }} @ ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        scala: [3.5.2]
        java: [zulu@21]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: Ignore line ending differences in git
        if: contains(runner.os, 'windows')
        shell: bash
        run: git config --global core.autocrlf false

      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: coursier/setup-action@v1

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install sbt
        shell: bash
        run: |
          cs install sbt
          echo "$HOME/.local/share/coursier/bin" >> $GITHUB_PATH
          sbt sbtVersion

      - name: sbt update
        if: matrix.java == 'zulu@21' && steps.setup-java-zulu-21.outputs.cache-hit == 'false'
        shell: bash
        run: sbt +update

      - name: Build project
        run: sbt '++ ${{ matrix.scala }}' coverage test

      - run: sbt '++ ${{ matrix.scala }}' coverageReport

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          fail-on-error: false # Fail if upload fails
          coverage-threshold: 85 # Minimum coverage percentage required
        env:
          COVERALLS_GIT_BRANCH: ${{ github.ref_name }} # Dynamically sets the branch name
