name: Gregs Scala CI

on: ["push", "pull_request"]

jobs:
  build:
    name: ScalaJack CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: '13.0.1'
    - name: Run tests and generate coverage report
      uses: lokkju/github-action-sbt@master
      with:
        commands: '+ test' clean coverage test coverageReport coverageAggregate
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_SCALAJACK }}